In [1]:
import pandas as pd
import numpy as np

In [2]:
df_work = pd.read_csv('../data/split_tabs/work.csv')
df_work.head(5)

   work_id  YearsCode  YearsCodePro  ComputerSkills MainBranch  candidate_id
0        0          7             4               4        Dev             0
1        1         12             5              12        Dev             1
2        2         15             6               7        Dev             2
3        3          9             6              13        Dev             3
4        4         40            30               2     NotDev             4

In [3]:
df_skills_candidate = pd.read_csv('../data/split_tabs/skills_candidate.csv')

In [4]:
df_work_skills_temp = df_work.merge(df_skills_candidate,'inner',on='candidate_id')
df_work_skills_temp.head(5)

,work_id,YearsCode,YearsCodePro,ComputerSkills,MainBranch,candidate_id,skill_name
0,0,7,4,4,Dev,0,C++
1,0,7,4,4,Dev,0,Python
2,0,7,4,4,Dev,0,Git
3,0,7,4,4,Dev,0,PostgreSQL
4,1,12,5,12,Dev,1,Bash/Shell

In [5]:
df_skills = pd.read_csv('../data/split_tabs/skills.csv')

In [6]:
df_work_skills = df_work_skills_temp.merge(df_skills,'inner',on='skill_name')
df_work_skills.head(15)

,work_id,YearsCode,YearsCodePro,ComputerSkills,MainBranch,candidate_id,skill_name,skills_id
0,0,7,4,4,Dev,0,C++,0
1,0,7,4,4,Dev,0,Python,1
2,0,7,4,4,Dev,0,Git,2
3,0,7,4,4,Dev,0,PostgreSQL,3
4,1,12,5,12,Dev,1,Bash/Shell,4
5,1,12,5,12,Dev,1,HTML/CSS,5
6,1,12,5,12,Dev,1,JavaScript,6
7,1,12,5,12,Dev,1,Node.js,7
8,1,12,5,12,Dev,1,SQL,8
9,1,12,5,12,Dev,1,TypeScript,9
10,1,12,5,12,Dev,1,Git,2
11,1,12,5,12,Dev,1,Express,10
12,1,12,5,12,Dev,1,React.js,11
13,1,12,5,12,Dev,1,Vue.js,12
14,1,12,5,12,Dev,1,AWS,13

In [7]:
df_work_skills[df_work_skills['skill_name']=='Python']

,work_id,YearsCode,YearsCodePro,ComputerSkills,MainBranch,candidate_id,skill_name,skills_id
1,0,7,4,4,Dev,0,Python,1
37,4,40,30,2,NotDev,4,Python,1
39,5,9,2,5,Dev,5,Python,1
61,7,14,5,4,NotDev,7,Python,1
64,8,39,21,3,Dev,8,Python,1
...,...,...,...,...,...,...,...,...
986277,73382,6,3,13,Dev,73382,Python,1
986287,73383,30,20,12,Dev,73383,Python,1
986340,73387,20,16,8,Dev,73387,Python,1
986380,73391,32,21,7,NotDev,73391,Python,1
986462,73398,4,2,11,Dev,73398,Python,1

In [8]:
df_work_skills[df_work_skills['candidate_id']==1]

,work_id,YearsCode,YearsCodePro,ComputerSkills,MainBranch,candidate_id,skill_name,skills_id
4,1,12,5,12,Dev,1,Bash/Shell,4
5,1,12,5,12,Dev,1,HTML/CSS,5
6,1,12,5,12,Dev,1,JavaScript,6
7,1,12,5,12,Dev,1,Node.js,7
8,1,12,5,12,Dev,1,SQL,8
9,1,12,5,12,Dev,1,TypeScript,9
10,1,12,5,12,Dev,1,Git,2
11,1,12,5,12,Dev,1,Express,10
12,1,12,5,12,Dev,1,React.js,11
13,1,12,5,12,Dev,1,Vue.js,12
14,1,12,5,12,Dev,1,AWS,13
15,1,12,5,12,Dev,1,PostgreSQL,3

In [9]:
df_work_skills = df_work_skills[['work_id', 'skills_id']]
df_work_skills.head(5)

   work_id  skills_id
0        0          0
1        0          1
2        0          2
3        0          3
4        1          4

In [10]:
df_work_skills[df_work_skills['skills_id']==1]

        work_id  skills_id
1             0          1
37            4          1
39            5          1
61            7          1
64            8          1
...         ...        ...
986277    73382          1
986287    73383          1
986340    73387          1
986380    73391          1
986462    73398          1

[31159 rows x 2 columns]

In [14]:
df_work_skills.index.name = 'work_skills_id'

In [15]:
df_work_skills.to_csv('../data/split_tabs/work_skills.csv')
df_work_skills.head(5)

                work_id  skills_id
work_skills_id
0                     0          0
1                     0          1
2                     0          2
3                     0          3
4                     1          4