In [15]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv('../data/processed/stackoverflow_full.csv')

In [19]:
df.head(5)

,candidate_id,Age,Accessibility,EdLevel,Employment,Gender,MentalHealth,MainBranch,YearsCode,YearsCodePro,Country,PreviousSalary,HaveWorkedWith,ComputerSkills,Employed
0,0,<35,No,Master,1,Man,No,Dev,7,4,Sweden,51552.0,C++;Python;Git;PostgreSQL,4,0
1,1,<35,No,Undergraduate,1,Man,No,Dev,12,5,Spain,46482.0,Bash/Shell;HTML/CSS;JavaScript;Node.js;SQL;Typ...,12,1
2,2,<35,No,Master,1,Man,No,Dev,15,6,Germany,77290.0,C;C++;Java;Perl;Ruby;Git;Ruby on Rails,7,0
3,3,<35,No,Undergraduate,1,Man,No,Dev,9,6,Canada,46135.0,Bash/Shell;HTML/CSS;JavaScript;PHP;Ruby;SQL;Gi...,13,0
4,4,>35,No,PhD,0,Man,No,NotDev,40,30,Singapore,160932.0,C++;Python,2,0

In [22]:
df_candidate = df[['candidate_id', 'Age', 'Gender', 'Country']]
df_candidate.head(5)

   candidate_id  Age Gender    Country
0             0  <35    Man     Sweden
1             1  <35    Man      Spain
2             2  <35    Man    Germany
3             3  <35    Man     Canada
4             4  >35    Man  Singapore

In [24]:
df_candidate.to_csv('../data/split_tabs/candidate.csv',index=False)
df_candidate.head()

   candidate_id  Age Gender    Country
0             0  <35    Man     Sweden
1             1  <35    Man      Spain
2             2  <35    Man    Germany
3             3  <35    Man     Canada
4             4  >35    Man  Singapore