In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../data/processed/stackoverflow_full.csv')

In [14]:
df.head(5)

,candidate_id,Age,Accessibility,EdLevel,Employment,Gender,MentalHealth,MainBranch,YearsCode,YearsCodePro,Country,PreviousSalary,HaveWorkedWith,ComputerSkills,Employed
recruitment_id,,,,,,,,,,,,,,,
0,0,<35,No,Master,1,Man,No,Dev,7,4,Sweden,51552.0,C++;Python;Git;PostgreSQL,4,0
1,1,<35,No,Undergraduate,1,Man,No,Dev,12,5,Spain,46482.0,Bash/Shell;HTML/CSS;JavaScript;Node.js;SQL;Typ...,12,1
2,2,<35,No,Master,1,Man,No,Dev,15,6,Germany,77290.0,C;C++;Java;Perl;Ruby;Git;Ruby on Rails,7,0
3,3,<35,No,Undergraduate,1,Man,No,Dev,9,6,Canada,46135.0,Bash/Shell;HTML/CSS;JavaScript;PHP;Ruby;SQL;Gi...,13,0
4,4,>35,No,PhD,0,Man,No,NotDev,40,30,Singapore,160932.0,C++;Python,2,0

In [13]:
df.index.name = 'recruitment_id'

In [15]:
df_recruitment_information = df[['PreviousSalary','Employed', 'MentalHealth','candidate_id']]
df_recruitment_information.head(5)

                PreviousSalary  Employed MentalHealth  candidate_id
recruitment_id
0                      51552.0         0           No             0
1                      46482.0         1           No             1
2                      77290.0         0           No             2
3                      46135.0         0           No             3
4                     160932.0         0           No             4

In [16]:
df_recruitment_information.to_csv('../data/split_tabs/recruitment_information.csv')
df_recruitment_information.head()

                PreviousSalary  Employed MentalHealth  candidate_id
recruitment_id
0                      51552.0         0           No             0
1                      46482.0         1           No             1
2                      77290.0         0           No             2
3                      46135.0         0           No             3
4                     160932.0         0           No             4